name: Test API
on:
  workflow_dispatch:

jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Test API
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://api.github.com)
          echo "API Response code: $STATUS_CODE"
